version: "3.4"

services:
  ap_michal:
    image: openwrt/imagebuilder:ramips-mt7621-${OPENWRT_VERSION}
    volumes:
      - ./files/ap_michal:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      FILES="/mnt/files/" 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="ap_michal"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_LUCI} ${PACKAGES_REMOVE_PPP} ${PACKAGES_PROMETHEUS} ${PACKAGES_UBUS_HA_SCANNER} -dnsmasq"
      PROFILE=xiaomi_mi-router-3g
  ap_basement:
    image: openwrt/imagebuilder:ramips-mt7621-${OPENWRT_VERSION}
    volumes:
      - ./files/ap_basement:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      FILES="/mnt/files/" 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="ap_basement"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_LUCI} ${PACKAGES_REMOVE_PPP} ${PACKAGES_PROMETHEUS} ${PACKAGES_UBUS_HA_SCANNER} -dnsmasq"
      PROFILE=xiaomi_mi-router-4a-gigabit
  parents:
    image: openwrt/imagebuilder:ramips-mt7621-21.02.0
    volumes:
      - ./files/parents:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      FILES="/mnt/files/" 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="parents"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_LUCI} ${PACKAGES_REMOVE_PPP} ${PACKAGES_PROMETHEUS} ${PACKAGES_VPN}"
      PROFILE=xiaomi_mi-router-4a-gigabit
  summerhouse_rack:
    image: openwrt/imagebuilder:ramips-mt7621-${OPENWRT_VERSION}
    volumes:
      - ./files/summerhouse_rack:/mnt/files/
      - ./output:${OUTPUT_DIR}
    # kmod-nf-nathelper-extra for pptp passthrough https://forum.openwrt.org/t/solved-ar71xx-kernel-4-9-pptp-passthrough-not-working-tl-wr942n-v1/11162/15
    command: >
      make image 
      BIN_DIR="${OUTPUT_DIR}"
      FILES="/mnt/files/" 
      EXTRA_IMAGE_NAME="summerhouse_rack"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_LUCI} ${PACKAGES_REMOVE_PPP} ${PACKAGES_NCM_MODEM} ${PACKAGES_VPN} ${PACKAGES_PROMETHEUS} ${PACKAGES_UBUS_HA_SCANNER} mosquitto-nossl snmpd netcat ca-bundle luci-app-unbound luci-app-adblock unbound-control odhcpd -dnsmasq -odhcpd-ipv6only kmod-nf-nathelper-extra"
      PROFILE=xiaomi_mi-router-3g
  x0:
    image: openwrt/imagebuilder:ramips-mt7621-${OPENWRT_VERSION}
    volumes:
      # - ./files/summerhouse_rack:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="x0"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_LUCI} ${PACKAGES_REMOVE_PPP} ${PACKAGES_VPN} ${PACKAGES_PROMETHEUS} ddns-scripts luci-app-ddns"
      PROFILE=ubnt_edgerouter-x
