version: "3.6"
services:
  x1:
    image: openwrtorg/imagebuilder:ramips-mt7621-19.07-SNAPSHOT
    volumes:
      - ./files:/mnt/files/x1/
      - ./output:/mnt/output/
    command: >
      make image 
      FILES="/mnt/files/" 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="x1"
      PACKAGES="uhttpd rpcd-mod-file uhttpd-mod-ubus libiwinfo-lua luci-base luci-app-firewall luci-mod-admin-full luci-theme-bootstrap  -ppp -ppp-mod-pppoe -ip6tables -odhcp6c -kmod-ipv6 -kmod-ip6tables -odhcpd-ipv6only -dnsmasq vim tcpdump" 
      PROFILE=xiaomi_mir3g
  summerhouse_rack:
    image: openwrtorg/imagebuilder:ramips-mt7621-19.07.1
    volumes:
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="summerhouse_rack"
      PACKAGES="uhttpd rpcd-mod-file uhttpd-mod-ubus libiwinfo-lua luci-base luci-app-firewall luci-mod-admin-full luci-theme-bootstrap  -ppp -ppp-mod-pppoe -ip6tables -odhcp6c -kmod-ipv6 -kmod-ip6tables -odhcpd-ipv6only comgt-ncm kmod-usb-net-huawei-cdc-ncm luci-proto-ncm usb-modeswitch mosquitto-nossl snmpd vim tcpdump" 
      PROFILE=xiaomi_mir3g
