services:
  ap_michal:
    image: openwrt/imagebuilder:mediatek-mt7622-${OPENWRT_VERSION}
    volumes:
      - ./files/ap_michal:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      FILES="/mnt/files/" 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="ap_michal"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_REMOVE_PPP} ${PACKAGES_NON_ROUTER} ${PACKAGES_PROMETHEUS}"
      PROFILE=xiaomi_redmi-router-ax6s
      DISABLED_SERVICES="firewall"
  ap_basement:
    image: openwrt/imagebuilder:ramips-mt7621-${OPENWRT_VERSION}
    volumes:
      - ./files/ap_basement:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      FILES="/mnt/files/" 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="ap_basement"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_REMOVE_PPP} ${PACKAGES_NON_ROUTER} ${PACKAGES_PROMETHEUS}"
      PROFILE=xiaomi_mi-router-4a-gigabit
      DISABLED_SERVICES="firewall"
  parents:
    image: openwrt/imagebuilder:ramips-mt7621-${OPENWRT_VERSION}
    volumes:
      - ./files/parents:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      FILES="/mnt/files/" 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="parents"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_REMOVE_PPP} ${PACKAGES_PROMETHEUS} ${PACKAGES_VPN} ${PACKAGES_REMOVE_IPV6}"
      PROFILE=xiaomi_mi-router-4a-gigabit
  summerhouse_rack:
    image: openwrt/imagebuilder:ramips-mt7621-${OPENWRT_VERSION}
    volumes:
      - ./files/summerhouse_rack:/mnt/files/
      - ./output:${OUTPUT_DIR}
    # -odhcpd-ipv6only for unbound
    command: >
      make image 
      BIN_DIR="${OUTPUT_DIR}"
      FILES="/mnt/files/" 
      EXTRA_IMAGE_NAME="summerhouse_rack"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_REMOVE_PPP} ${PACKAGES_VPN} ${PACKAGES_PROMETHEUS} ${PACKAGES_UBUS_HA_SCANNER} mosquitto-nossl netcat ca-bundle luci-app-unbound luci-app-adblock unbound-control odhcpd -dnsmasq -odhcpd-ipv6only"
      PROFILE=xiaomi_mi-router-3g
  travel_router:
    image: openwrt/imagebuilder:ramips-mt7621-${OPENWRT_VERSION}
    volumes:
      - ./files/travel_router:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      FILES="/mnt/files/" 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="travel_router"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_REMOVE_PPP} ${PACKAGES_VPN} adguardhome qrencode travelmate luci-app-travelmate"
      PROFILE=xiaomi_mi-router-3g
  x0:
    image: openwrt/imagebuilder:ramips-mt7621-${OPENWRT_VERSION}
    volumes:
      # - ./files/summerhouse_rack:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="x0"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_REMOVE_PPP} ${PACKAGES_VPN} ${PACKAGES_PROMETHEUS} ddns-scripts luci-app-ddns avahi-daemon luci-app-wol ip"
      PROFILE=ubnt_edgerouter-x
