version: "3.4"
services:
  x1:
    image: openwrtorg/imagebuilder:ramips-mt7621-19.07-SNAPSHOT
    volumes:
      - ./files/x1:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      FILES="/mnt/files/" 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="x1"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_LUCI} ${PACKAGES_REMOVE_PPP} ${PACKAGES_REMOVE_IPV6} rpcd-mod-file -dnsmasq"
      PROFILE=xiaomi_mir3g
  summerhouse_rack:
    # image: openwrtorg/imagebuilder:ramips-mt7621-19.07-SNAPSHOT
    image: openwrt-imagebuilder:ramips-mt7621-19.07-SNAPSHOT
    volumes:
      - ./files/summerhouse_rack:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      BIN_DIR="${OUTPUT_DIR}"
      FILES="/mnt/files/" 
      EXTRA_IMAGE_NAME="summerhouse_rack"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_LUCI} ${PACKAGES_REMOVE_PPP} ${PACKAGES_REMOVE_IPV6} ${PACKAGES_NCM_MODEM} ${PACKAGES_VPN} mosquitto-nossl snmpd rpcd-mod-file netcat ca-bundle luci-app-unbound luci-app-adblock libustream-mbedtls unbound-control odhcpd -dnsmasq -odhcpd-ipv6only wireguard kmod-wireguard luci-app-wireguard"
      PROFILE=xiaomi_mir3g
