version: "3.6"
services:
  x1:
    image: openwrtorg/imagebuilder:ramips-mt7621-19.07-SNAPSHOT
    volumes:
      - ./files/x1:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      FILES="/mnt/files/" 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="x1"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_LUCI} ${PACKAGES_REMOVE_PPP} ${PACKAGES_REMOVE_IPV6} rpcd-mod-file -dnsmasq"
      PROFILE=xiaomi_mir3g
  summerhouse_rack:
    image: openwrtorg/imagebuilder:ramips-mt7621-19.07.1
    volumes:
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="summerhouse_rack"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_LUCI} ${PACKAGES_REMOVE_PPP} ${PACKAGES_REMOVE_IPV6} ${PACKAGES_NCM_MODEM} mosquitto-nossl snmpd" 
      PROFILE=xiaomi_mir3g
