version: "3.4"

# networks:
#     default:
#       external: true
#       name: host

services:
  michal_ap:
    image: openwrtorg/imagebuilder:ramips-mt7621-${OPENWRT_VERSION}
    volumes:
      - ./files/michal_ap:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      FILES="/mnt/files/" 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="michal_ap"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_LUCI} ${PACKAGES_REMOVE_PPP} ${PACKAGES_REMOVE_IPV6} ${PACKAGES_COLLECTD} rpcd-mod-file -dnsmasq"
      PROFILE=xiaomi_mir3g
  summerhouse_rack:
    image: openwrtorg/imagebuilder:ramips-mt7621-${OPENWRT_VERSION}
    # image: openwrt-imagebuilder:ramips-mt7621-19.07.3
    volumes:
      - ./files/summerhouse_rack:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      BIN_DIR="${OUTPUT_DIR}"
      FILES="/mnt/files/" 
      EXTRA_IMAGE_NAME="summerhouse_rack"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_LUCI} ${PACKAGES_REMOVE_PPP} ${PACKAGES_REMOVE_IPV6} ${PACKAGES_NCM_MODEM} ${PACKAGES_VPN} ${PACKAGES_COLLECTD} mosquitto-nossl snmpd rpcd-mod-file netcat ca-bundle luci-app-unbound luci-app-adblock libustream-mbedtls unbound-control odhcpd -dnsmasq -odhcpd-ipv6only kmod-nf-nathelper-extra"
      PROFILE=xiaomi_mir3g
  x0:
    image: openwrtorg/imagebuilder:ramips-mt7621-${OPENWRT_VERSION}
    volumes:
      # - ./files/summerhouse_rack:/mnt/files/
      - ./output:${OUTPUT_DIR}
    command: >
      make image 
      BIN_DIR="${OUTPUT_DIR}"
      EXTRA_IMAGE_NAME="x0"
      PACKAGES="${PACKAGES_DEFAULT} ${PACKAGES_LUCI} ${PACKAGES_REMOVE_PPP} ${PACKAGES_REMOVE_IPV6} ${PACKAGES_VPN} ${PACKAGES_COLLECTD}"
      PROFILE=ubnt-erx
