name: Build images

on:
  push:
    branches:
      - 'master'

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build all images
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
          chmod a+w output
          make
          ls -lah output
      - name: Archive output artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sysupgrade-files
          path: |
            output/**/*.sysupgrade.bin

